### ISSUE TITLE
VW_RJS_HARBOR doesn't compile

### ISSUE THREAD

**Issue by signal006** [tobiasarnhold/svg-in-apex#1]
The **VW_RJS_HARBOR** view needs **RJS_COORDINATE_HARBOR** table but this table isn't there.
Can you add it?
Thanks.

**Comment by sebastianreinig** [comment]
Its in this fiile:
https://github.com/tobiasarnhold/svg-in-apex/blob/master/source/ddl.sql

See on line 207: "CREATE TABLE "RJS_COORDINATE_HARBOR.."

Maybe u can send a screenshot of your objects in the schema to see what happend. Did the installation throw any errors?
